export const demoData = {
  kpis: {
    totalRevenue: {
      value: 2650000,
      trend: "+12.5%",
      subtext: "Total revenue this quarter",
    },
    totalLeads: {
      value: 245,
      trend: "+5.3%",
      subtext: "Active leads in pipeline",
    },
    conversionRate: {
      value: "32%",
      trend: "+2.1%",
      subtext: "Average conversion rate",
    },
  },
  teamMembers: [
    {
      id: "tm1",
      name: "Sarah Connor",
      email: "sarah@example.com",
      phone: "+1 (555) 123-4567",
      role: "Admin",
      leads: 45,
      deals: 15,
      revenue: 425000,
      conversion: "33",
    },
    {
      id: "tm2",
      name: "John Smith",
      email: "john@example.com",
      phone: "+1 (555) 234-5678",
      role: "Sales Rep",
      leads: 38,
      deals: 12,
      revenue: 320000,
      conversion: "32",
    },
    {
      id: "tm3",
      name: "Emma Davis",
      email: "emma@example.com",
      phone: "+1 (555) 345-6789",
      role: "Sales Rep",
      leads: 32,
      deals: 8,
      revenue: 180000,
      conversion: "25",
    },
    {
      id: "tm4",
      name: "Michael Brown",
      email: "michael@example.com",
      phone: "+1 (555) 456-7890",
      role: "Sales Rep",
      leads: 28,
      deals: 10,
      revenue: 275000,
      conversion: "36",
    },
  ],
  pipelineStages: [
    { stage: "New", count: 45 },
    { stage: "Contacted", count: 32 },
    { stage: "Qualified", count: 24 },
    { stage: "Proposal", count: 18 },
    { stage: "Negotiation", count: 12 },
  ],
  monthlyTargets: {
    revenue: {
      current: 1250000,
      target: 2000000,
      progress: 62.5,
    },
    deals: {
      current: 28,
      target: 50,
      progress: 56,
    },
    meetings: {
      current: 45,
      target: 60,
      progress: 75,
    },
  },
  recentActivity: [
    {
      id: "act1",
      action: "Deal Won",
      description: "Enterprise Package - TechCorp",
      value: 125000,
      time: "2 hours ago",
    },
    {
      id: "act2",
      action: "New Lead",
      description: "Marketing Campaign - Series A",
      value: 45000,
      time: "5 hours ago",
    },
    {
      id: "act3",
      action: "Meeting Scheduled",
      description: "Product Demo - StartupX",
      value: 75000,
      time: "Yesterday",
    },
  ],
} as const;
